### PR TITLE
sequence doesn't work when a windowless app has focus

### PR DESCRIPTION
**Pull request by aaronjensen**
Open Preview or Chrome, close all windows. Use something like:

```
bind i:cmd sequence focus 'iTerm'
```

With sequence, it doesn't work. Without it, it works.

### CODE REVIEW

**Comment by aaronjensen** [comment]
I can do what I want w/ a js config, so I'm quite happy. Loving slate so far. Thanks for taking the reins @mattr-

**Comment by mattr-** [comment]
I'm honestly not sure why we don't have a global per application AccessibilityWrapper object instead of creating new ones each time. I'll have to dig into this a bit more.

**Comment by mattr-** [comment]
I'm closing this one in favor of #45, which I just merged. If you could check to see if that one fixes your issue, that would be great!

Thanks for the contribution! :heart:

**Comment by aaronjensen** [comment]
@mattr- that looks like it'd fix my problem in a much better way, thanks for merging it.

**Pull request closed without merging**
